// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/pagination/pagination.proto" (package "bilibili.pagination", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/pagination/pagination.proto" (package "bilibili.pagination", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class FeedPagination$Type extends MessageType {
    constructor() {
        super("bilibili.pagination.FeedPagination", [
            { no: 1, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "offset", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "is_refresh", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.FeedPagination
 */
export const FeedPagination = new FeedPagination$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FeedPaginationReply$Type extends MessageType {
    constructor() {
        super("bilibili.pagination.FeedPaginationReply", [
            { no: 1, name: "next_offset", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "prev_offset", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "last_read_offset", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.FeedPaginationReply
 */
export const FeedPaginationReply = new FeedPaginationReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Pagination$Type extends MessageType {
    constructor() {
        super("bilibili.pagination.Pagination", [
            { no: 1, name: "page_size", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "next", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.Pagination
 */
export const Pagination = new Pagination$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PaginationReply$Type extends MessageType {
    constructor() {
        super("bilibili.pagination.PaginationReply", [
            { no: 1, name: "next", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "prev", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.PaginationReply
 */
export const PaginationReply = new PaginationReply$Type();
