// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/pagination/pagination.proto" (package "bilibili.pagination", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 分页信息
 *
 * @generated from protobuf message bilibili.pagination.FeedPagination
 */
export interface FeedPagination {
    /**
     * @generated from protobuf field: int32 page_size = 1;
     */
    pageSize: number;
    /**
     * @generated from protobuf field: string offset = 2;
     */
    offset: string;
    /**
     * @generated from protobuf field: bool is_refresh = 3;
     */
    isRefresh: boolean;
}
/**
 * 分页信息
 *
 * @generated from protobuf message bilibili.pagination.FeedPaginationReply
 */
export interface FeedPaginationReply {
    /**
     * @generated from protobuf field: string next_offset = 1;
     */
    nextOffset: string;
    /**
     * @generated from protobuf field: string prev_offset = 2;
     */
    prevOffset: string;
    /**
     * @generated from protobuf field: string last_read_offset = 3;
     */
    lastReadOffset: string;
}
/**
 * 分页信息
 *
 * @generated from protobuf message bilibili.pagination.Pagination
 */
export interface Pagination {
    /**
     * @generated from protobuf field: int32 page_size = 1;
     */
    pageSize: number;
    /**
     * @generated from protobuf field: string next = 2;
     */
    next: string;
}
/**
 * 分页信息
 *
 * @generated from protobuf message bilibili.pagination.PaginationReply
 */
export interface PaginationReply {
    /**
     * @generated from protobuf field: string next = 1;
     */
    next: string;
    /**
     * @generated from protobuf field: string prev = 2;
     */
    prev: string;
}
declare class FeedPagination$Type extends MessageType<FeedPagination> {
    constructor();
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.FeedPagination
 */
export declare const FeedPagination: FeedPagination$Type;
declare class FeedPaginationReply$Type extends MessageType<FeedPaginationReply> {
    constructor();
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.FeedPaginationReply
 */
export declare const FeedPaginationReply: FeedPaginationReply$Type;
declare class Pagination$Type extends MessageType<Pagination> {
    constructor();
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.Pagination
 */
export declare const Pagination: Pagination$Type;
declare class PaginationReply$Type extends MessageType<PaginationReply> {
    constructor();
}
/**
 * @generated MessageType for protobuf message bilibili.pagination.PaginationReply
 */
export declare const PaginationReply: PaginationReply$Type;
export {};
