// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,long_type_string,output_javascript
// @generated from protobuf file "bilibili/main/community/reply/v1/reply.proto" (package "bilibili.main.community.reply.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { SuggestEmotesResp } from "./reply";
import type { SuggestEmotesReq } from "./reply";
import type { ShareRepliesInfoResp } from "./reply";
import type { ShareRepliesInfoReq } from "./reply";
import type { UserCallbackReply } from "./reply";
import type { UserCallbackReq } from "./reply";
import type { ReplyInfoReply } from "./reply";
import type { ReplyInfoReq } from "./reply";
import type { AtSearchReply } from "./reply";
import type { AtSearchReq } from "./reply";
import type { SearchItemReply } from "./reply";
import type { SearchItemReq } from "./reply";
import type { SearchItemPreHookReply } from "./reply";
import type { SearchItemPreHookReq } from "./reply";
import type { PreviewListReply } from "./reply";
import type { PreviewListReq } from "./reply";
import type { DialogListReply } from "./reply";
import type { DialogListReq } from "./reply";
import type { DetailListReply } from "./reply";
import type { DetailListReq } from "./reply";
import type { MainListReply } from "./reply";
import type { MainListReq } from "./reply";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 评论区
 *
 * @generated from protobuf service bilibili.main.community.reply.v1.Reply
 */
export interface IReplyClient {
    /**
     * 主评论列表接口
     *
     * @generated from protobuf rpc: MainList
     */
    mainList(input: MainListReq, options?: RpcOptions): UnaryCall<MainListReq, MainListReply>;
    /**
     * 二级评论明细接口
     *
     * @generated from protobuf rpc: DetailList
     */
    detailList(input: DetailListReq, options?: RpcOptions): UnaryCall<DetailListReq, DetailListReply>;
    /**
     * 对话评论树接口
     *
     * @generated from protobuf rpc: DialogList
     */
    dialogList(input: DialogListReq, options?: RpcOptions): UnaryCall<DialogListReq, DialogListReply>;
    /**
     * 评论预览接口
     *
     * @generated from protobuf rpc: PreviewList
     */
    previewList(input: PreviewListReq, options?: RpcOptions): UnaryCall<PreviewListReq, PreviewListReply>;
    /**
     * 评论搜索item前置发布接口
     *
     * @generated from protobuf rpc: SearchItemPreHook
     */
    searchItemPreHook(input: SearchItemPreHookReq, options?: RpcOptions): UnaryCall<SearchItemPreHookReq, SearchItemPreHookReply>;
    /**
     * 评论搜索插入项目接口
     *
     * @generated from protobuf rpc: SearchItem
     */
    searchItem(input: SearchItemReq, options?: RpcOptions): UnaryCall<SearchItemReq, SearchItemReply>;
    /**
     * 评论at用户搜索接口
     *
     * @generated from protobuf rpc: AtSearch
     */
    atSearch(input: AtSearchReq, options?: RpcOptions): UnaryCall<AtSearchReq, AtSearchReply>;
    /**
     * 查询单条评论接口
     *
     * @generated from protobuf rpc: ReplyInfo
     */
    replyInfo(input: ReplyInfoReq, options?: RpcOptions): UnaryCall<ReplyInfoReq, ReplyInfoReply>;
    /**
     * 用户回调上报接口
     *
     * @generated from protobuf rpc: UserCallback
     */
    userCallback(input: UserCallbackReq, options?: RpcOptions): UnaryCall<UserCallbackReq, UserCallbackReply>;
    /**
     * 评论分享材料接口
     *
     * @generated from protobuf rpc: ShareRepliesInfo
     */
    shareRepliesInfo(input: ShareRepliesInfoReq, options?: RpcOptions): UnaryCall<ShareRepliesInfoReq, ShareRepliesInfoResp>;
    /**
     * 评论表情推荐列表接口
     *
     * @generated from protobuf rpc: SuggestEmotes
     */
    suggestEmotes(input: SuggestEmotesReq, options?: RpcOptions): UnaryCall<SuggestEmotesReq, SuggestEmotesResp>;
}
/**
 * 评论区
 *
 * @generated from protobuf service bilibili.main.community.reply.v1.Reply
 */
export declare class ReplyClient implements IReplyClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * 主评论列表接口
     *
     * @generated from protobuf rpc: MainList
     */
    mainList(input: MainListReq, options?: RpcOptions): UnaryCall<MainListReq, MainListReply>;
    /**
     * 二级评论明细接口
     *
     * @generated from protobuf rpc: DetailList
     */
    detailList(input: DetailListReq, options?: RpcOptions): UnaryCall<DetailListReq, DetailListReply>;
    /**
     * 对话评论树接口
     *
     * @generated from protobuf rpc: DialogList
     */
    dialogList(input: DialogListReq, options?: RpcOptions): UnaryCall<DialogListReq, DialogListReply>;
    /**
     * 评论预览接口
     *
     * @generated from protobuf rpc: PreviewList
     */
    previewList(input: PreviewListReq, options?: RpcOptions): UnaryCall<PreviewListReq, PreviewListReply>;
    /**
     * 评论搜索item前置发布接口
     *
     * @generated from protobuf rpc: SearchItemPreHook
     */
    searchItemPreHook(input: SearchItemPreHookReq, options?: RpcOptions): UnaryCall<SearchItemPreHookReq, SearchItemPreHookReply>;
    /**
     * 评论搜索插入项目接口
     *
     * @generated from protobuf rpc: SearchItem
     */
    searchItem(input: SearchItemReq, options?: RpcOptions): UnaryCall<SearchItemReq, SearchItemReply>;
    /**
     * 评论at用户搜索接口
     *
     * @generated from protobuf rpc: AtSearch
     */
    atSearch(input: AtSearchReq, options?: RpcOptions): UnaryCall<AtSearchReq, AtSearchReply>;
    /**
     * 查询单条评论接口
     *
     * @generated from protobuf rpc: ReplyInfo
     */
    replyInfo(input: ReplyInfoReq, options?: RpcOptions): UnaryCall<ReplyInfoReq, ReplyInfoReply>;
    /**
     * 用户回调上报接口
     *
     * @generated from protobuf rpc: UserCallback
     */
    userCallback(input: UserCallbackReq, options?: RpcOptions): UnaryCall<UserCallbackReq, UserCallbackReply>;
    /**
     * 评论分享材料接口
     *
     * @generated from protobuf rpc: ShareRepliesInfo
     */
    shareRepliesInfo(input: ShareRepliesInfoReq, options?: RpcOptions): UnaryCall<ShareRepliesInfoReq, ShareRepliesInfoResp>;
    /**
     * 评论表情推荐列表接口
     *
     * @generated from protobuf rpc: SuggestEmotes
     */
    suggestEmotes(input: SuggestEmotesReq, options?: RpcOptions): UnaryCall<SuggestEmotesReq, SuggestEmotesResp>;
}
