// @generated by protobuf-ts 2.9.1 with parameter generate_dependencies,optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/app/viewunite/v1/viewunite.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
/**
 * 统一视频信息接口 (7.41.0+)
 *
 *
 * rpc ArcRefresh(ArcRefreshReq) returns (ArcRefreshReply);
 * 视频详情页下方推荐
 * rpc RelatesFeed(RelatesFeedReq) returns (RelatesFeedReply);
 * 视频详情页
 * rpc View(ViewReq) returns (ViewReply);
 * 播放进度
 * rpc ViewProgress(ViewProgressReq) returns (ViewProgressReply);
 *
 * @generated from protobuf service bilibili.app.viewunite.v1.View
 */
export interface IViewClient {
}
/**
 * 统一视频信息接口 (7.41.0+)
 *
 *
 * rpc ArcRefresh(ArcRefreshReq) returns (ArcRefreshReply);
 * 视频详情页下方推荐
 * rpc RelatesFeed(RelatesFeedReq) returns (RelatesFeedReply);
 * 视频详情页
 * rpc View(ViewReq) returns (ViewReply);
 * 播放进度
 * rpc ViewProgress(ViewProgressReq) returns (ViewProgressReply);
 *
 * @generated from protobuf service bilibili.app.viewunite.v1.View
 */
export declare class ViewClient implements IViewClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
}
