// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/dagw/component/avatar/common/common.proto" (package "bilibili.dagw.component.avatar.common", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/dagw/component/avatar/common/common.proto" (package "bilibili.dagw.component.avatar.common", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf enum bilibili.dagw.component.avatar.common.ResourceSource.LocalRes
 */
export var ResourceSource_LocalRes;
(function (ResourceSource_LocalRes) {
    /**
     * @generated from protobuf enum value: LOCAL_RES_INVALID = 0;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["INVALID"] = 0] = "INVALID";
    /**
     * @generated from protobuf enum value: LOCAL_RES_ICON_VIP = 1;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["ICON_VIP"] = 1] = "ICON_VIP";
    /**
     * @generated from protobuf enum value: LOCAL_RES_ICON_SMALL_VIP = 2;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["ICON_SMALL_VIP"] = 2] = "ICON_SMALL_VIP";
    /**
     * @generated from protobuf enum value: LOCAL_RES_ICON_PERSONAL_VERIFY = 3;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["ICON_PERSONAL_VERIFY"] = 3] = "ICON_PERSONAL_VERIFY";
    /**
     * @generated from protobuf enum value: LOCAL_RES_ICON_ENTERPRISE_VERIFY = 4;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["ICON_ENTERPRISE_VERIFY"] = 4] = "ICON_ENTERPRISE_VERIFY";
    /**
     * @generated from protobuf enum value: LOCAL_RES_ICON_NFT_MAINLAND = 5;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["ICON_NFT_MAINLAND"] = 5] = "ICON_NFT_MAINLAND";
    /**
     * @generated from protobuf enum value: LOCAL_RES_DEFAULT_AVATAR = 6;
     */
    ResourceSource_LocalRes[ResourceSource_LocalRes["DEFAULT_AVATAR"] = 6] = "DEFAULT_AVATAR";
})(ResourceSource_LocalRes || (ResourceSource_LocalRes = {}));
// @generated message type with reflection information, may provide speed optimized methods
class BasicRenderSpec$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.BasicRenderSpec", [
            { no: 1, name: "opacity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.BasicRenderSpec
 */
export const BasicRenderSpec = new BasicRenderSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ColorConfig$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.ColorConfig", [
            { no: 1, name: "is_dark_mode_aware", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "day", kind: "message", T: () => ColorSpec },
            { no: 3, name: "night", kind: "message", T: () => ColorSpec }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.ColorConfig
 */
export const ColorConfig = new ColorConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ColorSpec$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.ColorSpec", [
            { no: 1, name: "argb", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.ColorSpec
 */
export const ColorSpec = new ColorSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LayerGeneralSpec$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.LayerGeneralSpec", [
            { no: 1, name: "pos_spec", kind: "message", T: () => PositionSpec },
            { no: 2, name: "size_spec", kind: "message", T: () => SizeSpec },
            { no: 3, name: "render_spec", kind: "message", T: () => BasicRenderSpec }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.LayerGeneralSpec
 */
export const LayerGeneralSpec = new LayerGeneralSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MaskProperty$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.MaskProperty", [
            { no: 1, name: "general_spec", kind: "message", T: () => LayerGeneralSpec },
            { no: 2, name: "mask_src", kind: "message", T: () => ResourceSource }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.MaskProperty
 */
export const MaskProperty = new MaskProperty$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NativeDrawRes$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.NativeDrawRes", [
            { no: 1, name: "draw_type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "fill_mode", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "color_config", kind: "message", T: () => ColorConfig },
            { no: 4, name: "edge_weight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.NativeDrawRes
 */
export const NativeDrawRes = new NativeDrawRes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PositionSpec$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.PositionSpec", [
            { no: 1, name: "coordinate_pos", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "axis_x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "axis_y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.PositionSpec
 */
export const PositionSpec = new PositionSpec$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoteRes$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.RemoteRes", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "bfs_style", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.RemoteRes
 */
export const RemoteRes = new RemoteRes$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResourceSource$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.ResourceSource", [
            { no: 1, name: "src_type", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "placeholder", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "remote", kind: "message", oneof: "res", T: () => RemoteRes },
            { no: 4, name: "local", kind: "enum", oneof: "res", T: () => ["bilibili.dagw.component.avatar.common.ResourceSource.LocalRes", ResourceSource_LocalRes, "LOCAL_RES_"] },
            { no: 5, name: "draw", kind: "message", oneof: "res", T: () => NativeDrawRes }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.ResourceSource
 */
export const ResourceSource = new ResourceSource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SizeSpec$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.common.SizeSpec", [
            { no: 1, name: "width", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "height", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.common.SizeSpec
 */
export const SizeSpec = new SizeSpec$Type();
