// @generated by protobuf-ts 2.9.6 with parameter generate_dependencies,long_type_string,output_javascript
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import { DM } from "./dm";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
/**
 * 弹幕
 *
 * @generated from protobuf service bilibili.community.service.dm.v1.DM
 */
export class DMClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = DM.typeName;
        this.methods = DM.methods;
        this.options = DM.options;
    }
    /**
     * 获取分段弹幕
     *
     * @generated from protobuf rpc: DmSegMobile(bilibili.community.service.dm.v1.DmSegMobileReq) returns (bilibili.community.service.dm.v1.DmSegMobileReply);
     */
    dmSegMobile(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * 客户端弹幕元数据 字幕、分段、防挡蒙版等
     *
     * @generated from protobuf rpc: DmView(bilibili.community.service.dm.v1.DmViewReq) returns (bilibili.community.service.dm.v1.DmViewReply);
     */
    dmView(input, options) {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * 修改弹幕配置
     *
     * @generated from protobuf rpc: DmPlayerConfig(bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (bilibili.community.service.dm.v1.Response);
     */
    dmPlayerConfig(input, options) {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * ott弹幕列表
     *
     * @generated from protobuf rpc: DmSegOtt(bilibili.community.service.dm.v1.DmSegOttReq) returns (bilibili.community.service.dm.v1.DmSegOttReply);
     */
    dmSegOtt(input, options) {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * SDK弹幕列表
     *
     * @generated from protobuf rpc: DmSegSDK(bilibili.community.service.dm.v1.DmSegSDKReq) returns (bilibili.community.service.dm.v1.DmSegSDKReply);
     */
    dmSegSDK(input, options) {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DmExpoReport(bilibili.community.service.dm.v1.DmExpoReportReq) returns (bilibili.community.service.dm.v1.DmExpoReportRes);
     */
    dmExpoReport(input, options) {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
}
