// @generated by protobuf-ts 2.9.6 with parameter generate_dependencies,long_type_string,output_javascript
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import type { DmExpoReportRes } from "./dm";
import type { DmExpoReportReq } from "./dm";
import type { DmSegSDKReply } from "./dm";
import type { DmSegSDKReq } from "./dm";
import type { DmSegOttReply } from "./dm";
import type { DmSegOttReq } from "./dm";
import type { Response } from "./dm";
import type { DmPlayerConfigReq } from "./dm";
import type { DmViewReply } from "./dm";
import type { DmViewReq } from "./dm";
import type { DmSegMobileReply } from "./dm";
import type { DmSegMobileReq } from "./dm";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 弹幕
 *
 * @generated from protobuf service bilibili.community.service.dm.v1.DM
 */
export interface IDMClient {
    /**
     * 获取分段弹幕
     *
     * @generated from protobuf rpc: DmSegMobile(bilibili.community.service.dm.v1.DmSegMobileReq) returns (bilibili.community.service.dm.v1.DmSegMobileReply);
     */
    dmSegMobile(input: DmSegMobileReq, options?: RpcOptions): UnaryCall<DmSegMobileReq, DmSegMobileReply>;
    /**
     * 客户端弹幕元数据 字幕、分段、防挡蒙版等
     *
     * @generated from protobuf rpc: DmView(bilibili.community.service.dm.v1.DmViewReq) returns (bilibili.community.service.dm.v1.DmViewReply);
     */
    dmView(input: DmViewReq, options?: RpcOptions): UnaryCall<DmViewReq, DmViewReply>;
    /**
     * 修改弹幕配置
     *
     * @generated from protobuf rpc: DmPlayerConfig(bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (bilibili.community.service.dm.v1.Response);
     */
    dmPlayerConfig(input: DmPlayerConfigReq, options?: RpcOptions): UnaryCall<DmPlayerConfigReq, Response>;
    /**
     * ott弹幕列表
     *
     * @generated from protobuf rpc: DmSegOtt(bilibili.community.service.dm.v1.DmSegOttReq) returns (bilibili.community.service.dm.v1.DmSegOttReply);
     */
    dmSegOtt(input: DmSegOttReq, options?: RpcOptions): UnaryCall<DmSegOttReq, DmSegOttReply>;
    /**
     * SDK弹幕列表
     *
     * @generated from protobuf rpc: DmSegSDK(bilibili.community.service.dm.v1.DmSegSDKReq) returns (bilibili.community.service.dm.v1.DmSegSDKReply);
     */
    dmSegSDK(input: DmSegSDKReq, options?: RpcOptions): UnaryCall<DmSegSDKReq, DmSegSDKReply>;
    /**
     * @generated from protobuf rpc: DmExpoReport(bilibili.community.service.dm.v1.DmExpoReportReq) returns (bilibili.community.service.dm.v1.DmExpoReportRes);
     */
    dmExpoReport(input: DmExpoReportReq, options?: RpcOptions): UnaryCall<DmExpoReportReq, DmExpoReportRes>;
}
/**
 * 弹幕
 *
 * @generated from protobuf service bilibili.community.service.dm.v1.DM
 */
export declare class DMClient implements IDMClient, ServiceInfo {
    private readonly _transport;
    typeName: any;
    methods: any;
    options: any;
    constructor(_transport: RpcTransport);
    /**
     * 获取分段弹幕
     *
     * @generated from protobuf rpc: DmSegMobile(bilibili.community.service.dm.v1.DmSegMobileReq) returns (bilibili.community.service.dm.v1.DmSegMobileReply);
     */
    dmSegMobile(input: DmSegMobileReq, options?: RpcOptions): UnaryCall<DmSegMobileReq, DmSegMobileReply>;
    /**
     * 客户端弹幕元数据 字幕、分段、防挡蒙版等
     *
     * @generated from protobuf rpc: DmView(bilibili.community.service.dm.v1.DmViewReq) returns (bilibili.community.service.dm.v1.DmViewReply);
     */
    dmView(input: DmViewReq, options?: RpcOptions): UnaryCall<DmViewReq, DmViewReply>;
    /**
     * 修改弹幕配置
     *
     * @generated from protobuf rpc: DmPlayerConfig(bilibili.community.service.dm.v1.DmPlayerConfigReq) returns (bilibili.community.service.dm.v1.Response);
     */
    dmPlayerConfig(input: DmPlayerConfigReq, options?: RpcOptions): UnaryCall<DmPlayerConfigReq, Response>;
    /**
     * ott弹幕列表
     *
     * @generated from protobuf rpc: DmSegOtt(bilibili.community.service.dm.v1.DmSegOttReq) returns (bilibili.community.service.dm.v1.DmSegOttReply);
     */
    dmSegOtt(input: DmSegOttReq, options?: RpcOptions): UnaryCall<DmSegOttReq, DmSegOttReply>;
    /**
     * SDK弹幕列表
     *
     * @generated from protobuf rpc: DmSegSDK(bilibili.community.service.dm.v1.DmSegSDKReq) returns (bilibili.community.service.dm.v1.DmSegSDKReply);
     */
    dmSegSDK(input: DmSegSDKReq, options?: RpcOptions): UnaryCall<DmSegSDKReq, DmSegSDKReply>;
    /**
     * @generated from protobuf rpc: DmExpoReport(bilibili.community.service.dm.v1.DmExpoReportReq) returns (bilibili.community.service.dm.v1.DmExpoReportRes);
     */
    dmExpoReport(input: DmExpoReportReq, options?: RpcOptions): UnaryCall<DmExpoReportReq, DmExpoReportRes>;
}
