// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/dagw/component/avatar/v1/plugin.proto" (package "bilibili.dagw.component.avatar.v1.plugin", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,output_javascript
// @generated from protobuf file "bilibili/dagw/component/avatar/v1/plugin.proto" (package "bilibili.dagw.component.avatar.v1.plugin", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { ColorConfig } from "../common/common";
// @generated message type with reflection information, may provide speed optimized methods
class CommentDoubleClickConfig$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig", [
            { no: 1, name: "interaction", kind: "message", T: () => Interaction },
            { no: 2, name: "animation_scale", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.CommentDoubleClickConfig
 */
export const CommentDoubleClickConfig = new CommentDoubleClickConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GyroConfig$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.GyroConfig", [
            { no: 1, name: "gyroscope", kind: "message", T: () => NFTImageV2 }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.GyroConfig
 */
export const GyroConfig = new GyroConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GyroscopeContentV2$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2", [
            { no: 1, name: "file_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "scale", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "physical_orientation", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PhysicalOrientationV2 }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.GyroscopeContentV2
 */
export const GyroscopeContentV2 = new GyroscopeContentV2$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GyroscopeEntityV2$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2", [
            { no: 1, name: "display_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "contents", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GyroscopeContentV2 }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.GyroscopeEntityV2
 */
export const GyroscopeEntityV2 = new GyroscopeEntityV2$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Interaction$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.Interaction", [
            { no: 1, name: "nft_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "itype", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "metadata_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.Interaction
 */
export const Interaction = new Interaction$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LiveAnimeConfig$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig", [
            { no: 1, name: "is_live", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeConfig
 */
export const LiveAnimeConfig = new LiveAnimeConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LiveAnimeItem$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem", [
            { no: 1, name: "color", kind: "message", T: () => ColorConfig },
            { no: 2, name: "start_ratio", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "end_ratio", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "start_stroke", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "start_opacity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "phase", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.LiveAnimeItem
 */
export const LiveAnimeItem = new LiveAnimeItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NFTImageV2$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.NFTImageV2", [
            { no: 1, name: "gyroscope", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GyroscopeEntityV2 }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.NFTImageV2
 */
export const NFTImageV2 = new NFTImageV2$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PhysicalOrientationAnimation$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bezier", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationAnimation
 */
export const PhysicalOrientationAnimation = new PhysicalOrientationAnimation$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PhysicalOrientationV2$Type extends MessageType {
    constructor() {
        super("bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "animations", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PhysicalOrientationAnimation }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.dagw.component.avatar.v1.plugin.PhysicalOrientationV2
 */
export const PhysicalOrientationV2 = new PhysicalOrientationV2$Type();
