// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "bilibili/app/dynamic/v2/dynamic.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 动态综合页-响应
 *
 * @generated from protobuf message DynAllReply
 */
export interface DynAllReply {
    /**
     * 卡片列表
     *
     * @generated from protobuf field: DynamicList dynamic_list = 1;
     */
    dynamicList?: DynamicList;
    /**
     * 顶部up list
     *
     * @generated from protobuf field: CardVideoUpList up_list = 2;
     */
    upList?: CardVideoUpList;
    /**
     * 话题广场
     *
     * @generated from protobuf field: TopicList topic_list = 3;
     */
    topicList?: TopicList;
}
/**
 * 动态视频页-响应
 *
 * @generated from protobuf message DynVideoReply
 */
export interface DynVideoReply {
    /**
     * 动态卡片
     *
     * @generated from protobuf field: CardVideoUpList video_up_list = 2;
     */
    videoUpList?: CardVideoUpList;
}
/**
 * 动态卡片列表
 *
 * @generated from protobuf message DynamicList
 */
export interface DynamicList {
    /**
     * 动态列表
     *
     * @generated from protobuf field: repeated DynamicItem list = 1;
     */
    list: DynamicItem[];
}
/**
 * 视频页-最近访问
 *
 * @generated from protobuf message CardVideoUpList
 */
export interface CardVideoUpList {
    /**
     * 标题展示文案
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
}
/**
 * 综合页-话题广场
 *
 * @generated from protobuf message TopicList
 */
export interface TopicList {
    /**
     * 模块标题
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
}
/**
 * 动态卡片
 *
 * @generated from protobuf message DynamicItem
 */
export interface DynamicItem {
    /**
     * 动态卡片类型
     *
     * @generated from protobuf field: DynamicType card_type = 1;
     */
    cardType: DynamicType;
}
/**
 * @generated from protobuf enum DynamicType
 */
export declare enum DynamicType {
    /**
     * 占位
     *
     * @generated from protobuf enum value: dyn_none = 0;
     */
    dyn_none = 0,
    /**
     * 广告卡
     *
     * @generated from protobuf enum value: ad = 15;
     */
    ad = 15
}
declare class DynAllReply$Type extends MessageType<DynAllReply> {
    constructor();
    create(value?: PartialMessage<DynAllReply>): DynAllReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynAllReply): DynAllReply;
    internalBinaryWrite(message: DynAllReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message DynAllReply
 */
export declare const DynAllReply: DynAllReply$Type;
declare class DynVideoReply$Type extends MessageType<DynVideoReply> {
    constructor();
    create(value?: PartialMessage<DynVideoReply>): DynVideoReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynVideoReply): DynVideoReply;
    internalBinaryWrite(message: DynVideoReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message DynVideoReply
 */
export declare const DynVideoReply: DynVideoReply$Type;
declare class DynamicList$Type extends MessageType<DynamicList> {
    constructor();
    create(value?: PartialMessage<DynamicList>): DynamicList;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynamicList): DynamicList;
    internalBinaryWrite(message: DynamicList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message DynamicList
 */
export declare const DynamicList: DynamicList$Type;
declare class CardVideoUpList$Type extends MessageType<CardVideoUpList> {
    constructor();
    create(value?: PartialMessage<CardVideoUpList>): CardVideoUpList;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardVideoUpList): CardVideoUpList;
    internalBinaryWrite(message: CardVideoUpList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message CardVideoUpList
 */
export declare const CardVideoUpList: CardVideoUpList$Type;
declare class TopicList$Type extends MessageType<TopicList> {
    constructor();
    create(value?: PartialMessage<TopicList>): TopicList;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TopicList): TopicList;
    internalBinaryWrite(message: TopicList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message TopicList
 */
export declare const TopicList: TopicList$Type;
declare class DynamicItem$Type extends MessageType<DynamicItem> {
    constructor();
    create(value?: PartialMessage<DynamicItem>): DynamicItem;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DynamicItem): DynamicItem;
    internalBinaryWrite(message: DynamicItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message DynamicItem
 */
export declare const DynamicItem: DynamicItem$Type;
export {};
