// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,long_type_number,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,force_optimize_code_size,long_type_number,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { History } from "../../../playershared/playershared";
import { QnTrialInfo } from "../../../playershared/playershared";
import { PlayArc } from "../../../playershared/playershared";
import { Any } from "../../../../google/protobuf/any";
import { Event } from "../../../playershared/playershared";
import { PlayDeviceConf } from "../../../playershared/playershared";
import { PlayArcConf } from "../../../playershared/playershared";
import { VodInfo } from "../../../playershared/playershared";
import { VideoVod } from "../../../playershared/playershared";
// @generated message type with reflection information, may provide speed optimized methods
class PlayViewUniteReq$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.PlayViewUniteReq", [
            { no: 1, name: "vod", kind: "message", T: () => VideoVod },
            { no: 2, name: "spmid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "from_spmid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "extra_content", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.PlayViewUniteReq
 */
export const PlayViewUniteReq = new PlayViewUniteReq$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlayViewUniteReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.playerunite.v1.PlayViewUniteReply", [
            { no: 1, name: "vod_info", kind: "message", T: () => VodInfo },
            { no: 2, name: "play_arc_conf", kind: "message", T: () => PlayArcConf },
            { no: 3, name: "play_device_conf", kind: "message", T: () => PlayDeviceConf },
            { no: 4, name: "event", kind: "message", T: () => Event },
            { no: 5, name: "supplement", kind: "message", T: () => Any },
            { no: 6, name: "play_arc", kind: "message", T: () => PlayArc },
            { no: 7, name: "qn_trial_info", kind: "message", T: () => QnTrialInfo },
            { no: 8, name: "history", kind: "message", T: () => History }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export const PlayViewUniteReply = new PlayViewUniteReply$Type();
/**
 * @generated ServiceType for protobuf service bilibili.app.playerunite.v1.Player
 */
export const Player = new ServiceType("bilibili.app.playerunite.v1.Player", [
    { name: "PlayViewUnite", options: {}, I: PlayViewUniteReq, O: PlayViewUniteReply }
]);
