// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "bilibili/app/playerunite/v1/playerunite.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import { Player } from "./playerunite";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
/**
 * 统一视频url
 *
 * @generated from protobuf service bilibili.app.playerunite.v1.Player
 */
export class PlayerClient {
    constructor(_transport) {
        this._transport = _transport;
        this.typeName = Player.typeName;
        this.methods = Player.methods;
        this.options = Player.options;
    }
    /**
     * 视频地址
     *
     * @generated from protobuf rpc: PlayViewUnite(bilibili.app.playerunite.v1.PlayViewUniteReq) returns (bilibili.app.playerunite.v1.PlayViewUniteReply);
     */
    playViewUnite(input, options) {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept("unary", this._transport, method, opt, input);
    }
}
